import 'package:animo/models/filter_options/input_option.dart';
import 'package:animo/models/filter_options/multiselect_option.dart';
import 'package:animo/models/filter_options/select_item.dart';
import 'package:animo/models/filter_options/select_option.dart';

final mangaGenres = [
  SelectItem('4-Koma', '4-koma'),
  SelectItem('Action', 'action'),
  SelectItem('Adaptation', 'adaptation'),
  SelectItem('Adult', 'adult'),
  SelectItem('Adventure', 'adventure'),
  SelectItem('Aliens', 'aliens'),
  SelectItem('Animals', 'animals'),
  SelectItem('Anthology', 'anthology'),
  SelectItem('Award Winning', 'award-winning'),
  SelectItem('Comedy', 'comedy'),
  SelectItem('Cooking', 'cooking'),
  SelectItem('Crime', 'crime'),
  SelectItem('Crossdressing', 'crossdressing'),
  SelectItem('Delinquents', 'delinquents'),
  SelectItem('Demons', 'demons'),
  SelectItem('Doujinshi', 'doujinshi'),
  SelectItem('Drama', 'drama'),
  SelectItem('Ecchi', 'ecchi'),
  SelectItem('Fan Colored', 'fan-colored'),
  SelectItem('Fantasy', 'fantasy'),
  SelectItem('Full Color', 'full-color'),
  SelectItem('Gender Bender', 'gender-bender'),
  SelectItem('Genderswap', 'genderswap'),
  SelectItem('Ghosts', 'ghosts'),
  SelectItem('Gore', 'gore'),
  SelectItem('Gyaru', 'gyaru'),
  SelectItem('Harem', 'harem'),
  SelectItem('Historical', 'historical'),
  SelectItem('Horror', 'horror'),
  SelectItem('Incest', 'incest'),
  SelectItem('Isekai', 'isekai'),
  SelectItem('Loli', 'loli'),
  SelectItem('Long Strip', 'long-strip'),
  SelectItem('Mafia', 'mafia'),
  SelectItem('Magic', 'magic'),
  SelectItem('Magical Girls', 'magical-girls'),
  SelectItem('Martial Arts', 'martial-arts'),
  SelectItem('Mature', 'mature'),
  SelectItem('Mecha', 'mecha'),
  SelectItem('Medical', 'medical'),
  SelectItem('Military', 'military'),
  SelectItem('Monster Girls', 'monster-girls'),
  SelectItem('Monsters', 'monsters'),
  SelectItem('Music', 'music'),
  SelectItem('Mystery', 'mystery'),
  SelectItem('Ninja', 'ninja'),
  SelectItem('Office Workers', 'office-workers'),
  SelectItem('Official Colored', 'official-colored'),
  SelectItem('Oneshot', 'oneshot'),
  SelectItem('Philosophical', 'philosophical'),
  SelectItem('Police', 'police'),
  SelectItem('Post-Apocalyptic', 'post-apocalyptic'),
  SelectItem('Psychological', 'psychological'),
  SelectItem('Reincarnation', 'reincarnation'),
  SelectItem('Reverse Harem', 'reverse-harem'),
  SelectItem('Romance', 'romance'),
  SelectItem('Samurai', 'samurai'),
  SelectItem('School Life', 'school-life'),
  SelectItem('Sci-Fi', 'sci-fi'),
  SelectItem('Sexual Violence', 'sexual-violence'),
  SelectItem('Shota', 'shota'),
  SelectItem('Shoujo Ai', 'shoujo-ai'),
  SelectItem('Shounen Ai', 'shounen-ai'),
  SelectItem('Slice of Life', 'slice-of-life'),
  SelectItem('Smut', 'smut'),
  SelectItem('Sports', 'sports'),
  SelectItem('Superhero', 'superhero'),
  SelectItem('Supernatural', 'supernatural'),
  SelectItem('Survival', 'survival'),
  SelectItem('Thriller', 'thriller'),
  SelectItem('Time Travel', 'time-travel'),
  SelectItem('Traditional Games', 'traditional-games'),
  SelectItem('Tragedy', 'tragedy'),
  SelectItem('User Created', 'user-created'),
  SelectItem('Vampires', 'vampires'),
  SelectItem('Video Games', 'video-games'),
  SelectItem('Villainess', 'villainess'),
  SelectItem('Virtual Reality', 'virtual-reality'),
  SelectItem('Web Comic', 'web-comic'),
  SelectItem('Wuxia', 'wuxia'),
  SelectItem('Yaoi', 'yaoi'),
  SelectItem('Yuri', 'yuri'),
  SelectItem('Zombies', 'zombies'),
];
final mangaDemographics = [
  SelectItem('Shounen', '1'),
  SelectItem('Shoujo', '2'),
  SelectItem('Seinen', '3'),
  SelectItem('Josei', '4'),
];
final mangaCreatedAts = [
  SelectItem('3 days ago', '3'),
  SelectItem('7 days ago', '7'),
  SelectItem('30 days ago', '30'),
  SelectItem('3 months ago', '90'),
  SelectItem('6 months ago', '180'),
  SelectItem('1 year ago', '365'),
  SelectItem('2 years ago', '730'),
];
final mangaTypes = [
  SelectItem('Manga', 'jp'),
  SelectItem('Manhwa', 'kr'),
  SelectItem('Manhua', 'cn'),
  SelectItem('others', 'others'),
];
final mangaStatuses = [
  SelectItem('All', null),
  SelectItem('Ongoing', '1'),
  SelectItem('Completed', '2'),
  SelectItem('Cancelled', '3'),
  SelectItem('Hiatus', '4'),
];
final mangaSorts = [
  SelectItem('Latest', 'created_at'),
  SelectItem('Last updated', 'uploaded'),
  SelectItem('High rating', 'rating'),
  SelectItem('Popular', 'user_follow_count')
];

final mangaOptions = [
  MultiSelectOption('Genres', 'genres', mangaGenres),
  MultiSelectOption('Demographic', 'demographic', mangaDemographics),
  MultiSelectOption('Type', 'country', mangaTypes),
  SelectOption('Created at', 'time', mangaCreatedAts),
  InputOption('Minimum chapters', 'minimum'),
  SelectOption('Status', 'status', mangaStatuses),
  InputOption('From', 'from', title: 'From year, ex: 2010'),
  InputOption('To', 'to', title: 'To year, ex: 2021'),
  SelectOption('Sort', 'sort', mangaSorts),
];
